export const POPULAR_US_STOCKS = [
  { symbol: 'NVDA', name: '英伟达', company: 'NVIDIA' },
  { symbol: 'MSFT', name: '微软', company: 'Microsoft' },
  { symbol: 'AAPL', name: '苹果', company: 'Apple' },
  { symbol: 'TSLA', name: '特斯拉', company: 'Tesla' },
  { symbol: 'AMZN', name: '亚马逊', company: 'Amazon' },
  { symbol: 'GOOGL', name: '谷歌A', company: 'Alphabet' },
  { symbol: 'META', name: 'Meta', company: 'Meta' },
  { symbol: 'AVGO', name: '博通', company: 'Broadcom' },
  { symbol: 'AMD', name: '超威半导体', company: 'Advanced Micro Devices' },
  { symbol: 'TSM', name: '台积电', company: 'Taiwan Semiconductor' },
  { symbol: 'ASML', name: '阿斯麦', company: 'ASML' },
  { symbol: 'QQQ', name: '纳斯达克100 ETF', company: 'Invesco QQQ' },
  { symbol: 'SPY', name: '标普500 ETF', company: 'SPDR S&P 500 ETF' },
  { symbol: 'TQQQ', name: '三倍做多纳指', company: 'ProShares UltraPro QQQ' },
  { symbol: 'PLTR', name: 'Palantir', company: 'Palantir' },
  { symbol: 'NFLX', name: '奈飞', company: 'Netflix' },
  { symbol: 'COST', name: '好市多', company: 'Costco' },
  { symbol: 'JPM', name: '摩根大通', company: 'JPMorgan Chase' },
  { symbol: 'BAC', name: '美国银行', company: 'Bank of America' },
  { symbol: 'V', name: 'Visa', company: 'Visa' },
  { symbol: 'MA', name: '万事达', company: 'Mastercard' },
  { symbol: 'ORCL', name: '甲骨文', company: 'Oracle' },
  { symbol: 'CRM', name: 'Salesforce', company: 'Salesforce' },
  { symbol: 'ADBE', name: 'Adobe', company: 'Adobe' },
  { symbol: 'NOW', name: 'ServiceNow', company: 'ServiceNow' },
  { symbol: 'SNOW', name: 'Snowflake', company: 'Snowflake' },
  { symbol: 'CRWD', name: 'CrowdStrike', company: 'CrowdStrike' },
  { symbol: 'PANW', name: 'Palo Alto', company: 'Palo Alto Networks' },
  { symbol: 'SHOP', name: 'Shopify', company: 'Shopify' },
  { symbol: 'IBKR', name: '盈透证券', company: 'Interactive Brokers' },
];

export const POPULAR_US_STOCK_SYMBOLS = new Set(POPULAR_US_STOCKS.map((item) => item.symbol));
