export const STOCK_RSI_RISK_VERSION = 'rsi6-risk-v2';
export const DIVERGENCE_RISK_LEVELS = Object.freeze(['NONE', 'LOW', 'MEDIUM', 'HIGH']);

// Initial strategy parameters, not calibrated probabilities. All observations
// use completed trading records; price thresholds and recovery values are ratios.
export const STOCK_RSI_RISK_RULES = Object.freeze({
  BASE_FORMING: 30,
  BASE_CONFIRMED: 45,
  RSI_DIFFERENCE_MEDIUM: 8,
  RSI_DIFFERENCE_HIGH: 12,
  RSI_DIFFERENCE_VERY_HIGH: 16,
  RSI_STRENGTH_LOW: 5,
  RSI_STRENGTH_MEDIUM: 10,
  RSI_STRENGTH_HIGH: 15,
  RSI_STRENGTH_VERY_HIGH: 20,
  MAX_DIVERGENCE_STRENGTH: 25,
  HIGHER_HIGH_BONUS_THRESHOLD: 0.02,
  HIGHER_HIGH_BONUS: 5,
  BELOW_MA30_PENALTY: 10,
  FALLING_MA30_PENALTY: 5,
  MAX_MA30_ADJUSTMENT: 15,
  TREND_BULLISH_STRENGTHENING: -15,
  TREND_BULLISH_WEAKENING: 10,
  TREND_BEARISH_STRENGTHENING: 20,
  TREND_BEARISH_WEAKENING: 5,
  TREND_IMPROVING: -10,
  TREND_STRUCTURAL_WEAKENING: 15,
  TREND_STRENGTHENING: -15,
  TREND_WEAKENING: 20,
  TREND_STABLE: 0,
  PRICE_RECOVERY_LOW: 0.30,
  PRICE_RECOVERY_MEDIUM: 0.50,
  PRICE_RECOVERY_HIGH: 0.70,
  PRICE_RECOVERY_FULL: 0.80,
  PRICE_RECOVERY_LOW_ADJUSTMENT: -3,
  PRICE_RECOVERY_MEDIUM_ADJUSTMENT: -5,
  PRICE_RECOVERY_HIGH_ADJUSTMENT: -10,
  PRICE_RECOVERY_FULL_ADJUSTMENT: -15,
  RSI_RECOVERY_WIDE_TOLERANCE: 10,
  RSI_RECOVERY_CLOSE_TOLERANCE: 5,
  RSI_RECOVERY_NEAR_TOLERANCE: 2,
  RSI_RECOVERY_WIDE_ADJUSTMENT: -3,
  RSI_RECOVERY_CLOSE_ADJUSTMENT: -5,
  RSI_RECOVERY_NEAR_ADJUSTMENT: -10,
  RECOVERY_ADJUSTMENT_MIN: -20,
  TIME_DECAY_FIRST_AGE: 6,
  TIME_DECAY_SECOND_AGE: 11,
  TIME_DECAY_THIRD_AGE: 16,
  TIME_DECAY_FIRST_ADJUSTMENT: -5,
  TIME_DECAY_SECOND_ADJUSTMENT: -10,
  TIME_DECAY_THIRD_ADJUSTMENT: -15,
  DETERIORATION_LOOKBACK: 5,
  DETERIORATION_MA30_SLOPE_THRESHOLD: 0.001,
  MA_PRICE_MATCH_RELATIVE_TOLERANCE: 1e-8,
  RISK_LOW_MIN: 25,
  RISK_MEDIUM_MIN: 45,
  RISK_HIGH_MIN: 70,
  RISK_MIN: 0,
  RISK_MAX: 100,
});

export function resolveStockRsiRiskRules(overrides) {
  if (overrides !== undefined && (!overrides || typeof overrides !== 'object' || Array.isArray(overrides))) return null;
  if (overrides && Object.keys(overrides).some(key => !Object.hasOwn(STOCK_RSI_RISK_RULES, key))) return null;
  const rules = { ...STOCK_RSI_RISK_RULES, ...overrides };
  if (Object.values(rules).some(value => typeof value !== 'number' || !Number.isFinite(value))) return null;
  for (const key of ['DETERIORATION_LOOKBACK', 'TIME_DECAY_FIRST_AGE', 'TIME_DECAY_SECOND_AGE', 'TIME_DECAY_THIRD_AGE']) {
    if (!Number.isSafeInteger(rules[key]) || rules[key] <= 0) return null;
  }
  if (!(rules.TIME_DECAY_FIRST_AGE < rules.TIME_DECAY_SECOND_AGE && rules.TIME_DECAY_SECOND_AGE < rules.TIME_DECAY_THIRD_AGE)
    || !(rules.RSI_RECOVERY_NEAR_TOLERANCE >= 0 && rules.RSI_RECOVERY_NEAR_TOLERANCE < rules.RSI_RECOVERY_CLOSE_TOLERANCE
      && rules.RSI_RECOVERY_CLOSE_TOLERANCE < rules.RSI_RECOVERY_WIDE_TOLERANCE)
    || !(rules.RSI_DIFFERENCE_MEDIUM > 0 && rules.RSI_DIFFERENCE_MEDIUM < rules.RSI_DIFFERENCE_HIGH
      && rules.RSI_DIFFERENCE_HIGH < rules.RSI_DIFFERENCE_VERY_HIGH)
    || !(rules.PRICE_RECOVERY_LOW > 0 && rules.PRICE_RECOVERY_LOW < rules.PRICE_RECOVERY_MEDIUM
      && rules.PRICE_RECOVERY_MEDIUM < rules.PRICE_RECOVERY_HIGH
      && rules.PRICE_RECOVERY_HIGH < rules.PRICE_RECOVERY_FULL && rules.PRICE_RECOVERY_FULL <= 1)
    || !(rules.HIGHER_HIGH_BONUS_THRESHOLD > 0 && rules.HIGHER_HIGH_BONUS_THRESHOLD < 1)
    || !(rules.MAX_DIVERGENCE_STRENGTH >= 0 && rules.MAX_MA30_ADJUSTMENT >= 0 && rules.RECOVERY_ADJUSTMENT_MIN <= 0)
    || !(rules.DETERIORATION_MA30_SLOPE_THRESHOLD > 0 && rules.DETERIORATION_MA30_SLOPE_THRESHOLD < 1)
    || !(rules.MA_PRICE_MATCH_RELATIVE_TOLERANCE >= 0 && rules.MA_PRICE_MATCH_RELATIVE_TOLERANCE < 1)
    || !(rules.RISK_MIN === 0 && rules.RISK_MAX === 100 && rules.RISK_LOW_MIN > 0
      && rules.RISK_LOW_MIN < rules.RISK_MEDIUM_MIN && rules.RISK_MEDIUM_MIN < rules.RISK_HIGH_MIN
      && rules.RISK_HIGH_MIN <= rules.RISK_MAX)) return null;
  return rules;
}
