import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
const count = (source, pattern) => (source.match(pattern) || []).length;

const home = read('src/tabs/HomeTab.jsx');
const homeCss = read('src/tabs/HomeTab.css');
const watchlistDialogCss = read('src/tabs/HomeWatchlistDialogs.css');
const stockReportModalCss = read('src/components/StockReportModal.css');
const trades = read('src/tabs/TradesTab.jsx');
const tradesCss = read('src/tabs/TradesTab.css');
const positionProfitScenarioCss = read('src/tabs/PositionProfitScenario.css');
const assets = read('src/tabs/AnalysisTab.jsx');
const monthlyAssetTrendChart = read('src/components/MonthlyAssetTrendChart.jsx');
const reviewCss = read('src/tabs/ReviewTab.css');
const compoundDetail = read('src/pages/CompoundDetailPage.jsx');
const compoundDetailCss = read('src/pages/CompoundDetailPage.css');
const annualPlan = read('src/components/AnnualGoalPlan.jsx');
const annualPlanCss = read('src/components/AnnualGoalPlan.css');
const northStar = read('src/components/NorthStarGoalCard.jsx');
const northStarCss = read('src/components/NorthStarGoalCard.css');
const reviewGoalModalCss = read('src/components/ReviewGoalModal.css');
const reviewReadingDetails = read('src/components/ReviewReadingDetails.jsx');
const reviewReadingDetailsCss = read('src/components/ReviewReadingDetails.css');
const settings = read('src/tabs/SettingsTab.jsx');
const pnlReport = read('src/pages/PnlReportPage.jsx');
const stockDetail = read('src/pages/StockDetailPage.jsx');
const stockDetailCss = read('src/pages/StockDetailPage.css');
const watchlistDetail = read('src/pages/WatchlistStockDetailPage.jsx');
const watchlistDetailCss = read('src/pages/WatchlistStockDetailPage.css');
const stockDetailReportCss = read('src/components/StockDetailReportSections.css');
const competition = read('src/pages/CommunityCompetitionPage.jsx');
const waveTracker = read('src/pages/WaveTrackerPage.jsx');
const earningsDetail = read('src/pages/EarningsDetailPage.jsx');
const earningsGrowth = read('src/components/EarningsGrowthCard.jsx');
const earningsCalendar = read('src/tabs/EarningsCalendar.jsx');
const valuation = read('src/components/CompanyValuationCard.jsx');
const ma200History = read('src/components/Ma200RetestHistoryCard.jsx');
const stockComparison = read('src/components/StockReturnComparisonCard.jsx');
const stockComparisonCss = read('src/components/StockReturnComparisonCard.css');

test('persistent production modules share neutral black surface levels', () => {
  assert.ok(trades.includes('data-trades-net-assets-card="true"'));
  assert.ok(trades.includes('<section className="trades-report-hero"'), 'Trading should use its continuous report hero');
  assert.match(tradesCss, /\.trades-report\s*\{[^}]*color:\s*#e4e4e7;/, 'Trading report should use the neutral text palette');
  assert.doesNotMatch(tradesCss, /radial-gradient|linear-gradient|box-shadow/, 'Trading report surfaces should stay free of decorative glow');
  assert.ok(assets.includes("const ASSET_CARD = '#0b0c0e';"));
  assert.match(northStarCss, /\.north-star-card\s*\{[^}]*background:\s*#101112;/, 'north-star presentation should use its scoped neutral surface');
  assert.match(annualPlanCss, /\.annual-goal-plan \.ag-current-card\s*\{[^}]*border:\s*0;[^}]*background:\s*#101112;/, 'current annual plan should share the north-star neutral borderless surface');
  assert.match(reviewCss, /\.review-page\s*\{[^}]*--review-surface:\s*#101112;/, 'review reading sections should use the same scoped neutral surface');
  assert.match(reviewCss, /\.review-page \.review-entry\s*\{[^}]*background:\s*transparent;[^}]*border:\s*0;/, 'normal notes and logs should use quiet transparent reading rows');
  assert.match(reviewCss, /\.review-page \.review-entry\[data-pinned=true\]\s*\{[^}]*background:\s*var\(--review-surface\);/, 'pinned notes alone should use the raised neutral reading surface');
  assert.ok(compoundDetail.includes('<main className="compound-detail-page"'), 'compound details should use their independent page surface');
  assert.doesNotMatch(compoundDetail, /ReviewGoalModal|ActionModalCard/, 'compound details should not retain a dialog surface');
  assert.doesNotMatch(compoundDetail + compoundDetailCss, /UsFlagBackground|linearGradient|linear-gradient|radial-gradient|#f6b54b|#ffd18a/, 'compound details should not restore the old gold border or chart gradients');
  assert.ok(settings.includes('linear-gradient(145deg,#0b0c0e,#0b0c0e)'));
  assert.equal(count(settings, /bg-\[#0b0c0e\]/g), 2, 'settings rows and changelog should use the primary neutral surface');

  assert.equal(count(pnlReport, /bg-\[#0b0c0e\]/g), 4);
  assert.equal(count(pnlReport, /bg-\[#101114\]/g), 2);
  assert.match(stockDetail, /<main className="stock-detail-report"/, 'individual returns should use a continuous scoped report, not nested exterior cards');
  assert.match(stockDetailCss, /\.stock-detail-report\s*\{[^}]*max-width:\s*760px;[^}]*background:\s*#08090b;[^}]*color:\s*#e4e4e7;/);
  assert.match(stockDetailCss, /\.sdp-target-price\s*\{[^}]*color:\s*#e4e4e7;/, 'target amount should be a neutral personal plan, not a gold investment signal');
  assert.match(stockDetailCss, /\.sdp-range\[aria-pressed="true"\]\s*\{[^}]*background:\s*#1a1b1e;[^}]*color:\s*#e4e4e7;/);
  assert.doesNotMatch(stockDetailCss, /#0b0f14|#f6b54b|#ffd18a|linear-gradient|radial-gradient|box-shadow/);
  assert.match(watchlistDetail, /<main className="stock-report-page\b/, 'stock trends use the scoped continuous report surface, not a fixed count of boxed cards');
  assert.match(watchlistDetailCss, /\.stock-report-page\s*\{[^}]*background:\s*#08090b;/);
  assert.match(watchlistDetail, /<section className="stock-report-hero"/);
  assert.match(watchlistDetailCss, /\.stock-report-price\s*\{[^}]*color:\s*#f1f1f4;/, 'current price remains neutral while changes and the chart use market direction');
  assert.equal(count(competition, /bg-\[#0b0c0e\]/g), 5);
  assert.ok(waveTracker.includes('border border-[#1a2530] bg-[#0b0c0e]'));
  assert.equal(count(waveTracker, /bg-\[#0b0c0e\]/g), 3);

  assert.equal(count(earningsDetail, /bg-\[#0b0c0e\]/g), 6);
  assert.equal(count(earningsDetail, /bg-\[#101114\]/g), 1);
  assert.equal(count(earningsGrowth, /bg-\[#0b0c0e\]/g), 2);
  assert.ok(earningsCalendar.includes("? 'flex h-[calc(100dvh-env(safe-area-inset-top)-138px)] min-h-[560px] w-full flex-col rounded-[20px] border border-white/10 bg-[#0b0c0e]"));
  assert.ok(valuation.includes('rounded-2xl border border-white/[0.09] bg-[#0b0c0e]'));
  assert.ok(ma200History.includes('rounded-2xl border border-white/[0.09] bg-[#0b0c0e]'));
  assert.ok(stockComparison.includes('id="stock-return-comparison" className="stock-comparison-report"'));
  assert.match(stockComparisonCss, /\.stock-comparison-report\s*\{[^}]*border-top:\s*1px solid rgb\(255 255 255 \/ \.075\);[^}]*color:\s*#e4e4e7;/);
  assert.doesNotMatch(stockComparisonCss, /#0b0f14|#0d1118|#f6b54b|#ffd18a|linear-gradient|radial-gradient/);
});

test('stock-trend report variants are opt-in neutral sections without recoloring other card consumers', () => {
  for (const [component, section] of [[valuation, 'valuation'], [ma200History, 'ma200-retest']]) {
    assert.ok(component.includes("presentation = 'card'"), 'existing consumers retain their card presentation');
    assert.ok(component.includes("presentation === 'report'"));
    assert.ok(component.includes(`data-stock-detail-report-section={reportPresentation ? '${section}' : undefined}`));
  }
  assert.match(watchlistDetail, /<CompanyValuationCard\s+presentation="report"/);
  assert.match(watchlistDetail, /<Ma200RetestHistoryCard\s+presentation="report"/);
  const reportSurface = stockDetailReportCss.match(/section\[data-stock-detail-report-section\]\s*\{([^}]+)\}/)?.[1];
  assert.ok(reportSurface);
  assert.match(reportSurface, /border:\s*0;/);
  assert.match(reportSurface, /border-radius:\s*0;/);
  assert.match(reportSurface, /background:\s*transparent;/);
  assert.match(reportSurface, /box-shadow:\s*none;/);
});

test('actual asset amounts use soft white while semantic gold and the settings glow remain', () => {
  assert.ok(home.includes('data-home-net-assets="true"'));
  assert.ok(home.includes('home-report-net-amount text-white/[0.95] tabular-nums'));
  assert.ok(home.includes('className="home-report-decimal"'));
  assert.match(homeCss, /\.home-report-decimal\s*\{[^}]*color:\s*#83838c;[^}]*font-size:\s*\.64em;/, 'Home decimal suffix stays neutral and subordinate to the white headline');
  assert.ok(trades.includes('className="trades-report-net-amount"'));
  assert.match(tradesCss, /\.trades-report-decimal\s*\{[^}]*color:\s*#83838c;[^}]*font-size:\s*\.64em;/, 'Trading split decimals should match the new Home report hierarchy');
  assert.ok(assets.includes('tracking-normal text-white/[0.95] tabular-nums'));
  assert.ok(assets.includes('text-white/[0.95] tabular-nums') && assets.includes('≈ ¥{fmt(curSum, 0)}'));
  assert.ok(compoundDetail.includes('{fmt(selectedAsset)}'));
  assert.match(compoundDetailCss, /\.compound-detail-page \.compound-detail\s*\{[^}]*color:\s*#d9d9df;[^}]*font-variant-numeric:\s*tabular-nums;/, 'compound recorded assets should inherit neutral white tabular numbers');
  assert.match(compoundDetailCss, /\.cp-selected-asset dd\s*\{[^}]*color:\s*#e4e4e9;/, 'selected actual and projected asset amounts should keep their neutral light amount color');
  assert.ok(compoundDetail.includes("!currentShortfall && finite(difference) ? marketTextClass(difference, marketColorMode) : ''"), 'an unfinished current-year shortfall should retain a neutral color while recorded comparisons respect market colors');
  assert.ok(compoundDetail.includes('fmt(row.hasActual ? row.actualEndBalance : row.targetEndBalance)'));
  assert.match(compoundDetailCss, /\.cp-row-value strong\s*\{[^}]*color:\s*#c1c1ca;/, 'compound annual balances should use a neutral light amount color');
  assert.match(annualPlanCss, /\.annual-goal-plan\s*\{[^}]*color:\s*#f1f1f2;[^}]*font-variant-numeric:\s*tabular-nums;/, 'annual amounts should inherit neutral tabular number styling');
  assert.ok(annualPlan.includes('marketHexColor(currentYear.actualGain, marketColorMode)') && annualPlan.includes('marketHexColor(item.actualGain, marketColorMode)'), 'real annual gains should respect the user market-color convention');
  assert.match(northStarCss, /\.north-star-card\s*\{[^}]*color:\s*#f1f1f2;[^}]*font-variant-numeric:\s*tabular-nums;/, 'north-star headline and current amount should inherit neutral white tabular numbers');
  assert.ok(northStar.includes('goalMoney.main') && northStar.includes('goalMoney.decimal'), 'north-star headline should preserve its split-decimal amount');
  assert.doesNotMatch(northStar, /★|<Star\b/, 'north-star title should not restore a decorative star');
  assert.match(northStarCss, /\.ns-completion strong\s*\{[^}]*color:\s*#ff4b1f;/, 'north-star completion value should use system red');
  assert.match(northStarCss, /\.ns-progress-fill\s*\{[^}]*background:\s*#ff4b1f;/, 'north-star progress fill should match its completion value');
  assert.match(annualPlanCss, /\.annual-goal-plan \.ag-progress-fill\s*\{[^}]*background:\s*#ff4b1f;/, 'annual progress should share the quiet system-red north-star progress treatment');
  assert.doesNotMatch(annualPlanCss, /linear-gradient|radial-gradient|box-shadow/, 'annual presentation should not reintroduce decorative glow or gradients');
  assert.ok(settings.includes('radial-gradient(circle_at_50%_35%,rgba(33,65,122,0.13),transparent_45%)'));
});

test('sheets, tooltips, and chart markers keep their separate depth colors', () => {
  assert.equal(count(home, /panelClassName="watchlist-dialog watchlist-dialog-(add|edit)"/g), 2, 'both watchlist dialogs opt into the shared report-modal palette');
  assert.match(stockReportModalCss, /\.stock-report-modal\s*\{[^}]*background:\s*#101112;/, 'watchlist dialogs share the approved neutral-black report surface');
  assert.doesNotMatch(watchlistDialogCss, /#0b0f14|#f6b54b/, 'watchlist controls do not override the report palette with legacy blue or gold');
  const benchmarkStart = home.indexOf('{benchmarkMenuOpen && (');
  const benchmarkEnd = home.indexOf('<HomeWatchlistReport', benchmarkStart);
  assert.ok(benchmarkStart >= 0 && benchmarkEnd > benchmarkStart, 'benchmark assertions must be bounded to the actual picker');
  const benchmarkSheet = home.slice(benchmarkStart, benchmarkEnd);
  assert.ok(benchmarkSheet.includes('bg-[#101112]'), 'benchmark picker shares the approved goal-dialog neutral surface');
  assert.ok(benchmarkSheet.includes("row.selected ? 'bg-[#1b1c1e]'"));
  assert.ok(benchmarkSheet.includes('aria-pressed={row.selected}'));
  assert.ok(benchmarkSheet.includes('row.selected && <Check'));
  assert.ok(benchmarkSheet.includes("(Number(row.drawdown) >= 0) === (marketColorMode === 'redUpGreenDown')"), 'benchmark drawdowns honor the global up/down convention, not the old risk-depth colors');
  assert.ok(benchmarkSheet.includes("drawdownUsesRed ? 'text-[#ff604f]' : 'text-[#50c8a0]'"), 'benchmark colors match the new drawdown observation page');
  assert.doesNotMatch(benchmarkSheet, /text-rose-400|text-emerald-400|Number\(row\.drawdown\) <= -0\.05/);
  assert.doesNotMatch(benchmarkSheet, /#f6b54b|bg-emerald|rounded-2xl border|<SortIcon/, 'selection and sorting stay neutral without nested bordered cards');
  assert.ok(benchmarkSheet.includes('min-h-0 space-y-1 overflow-y-auto overscroll-contain'), 'only the options scroll inside the sheet');
  const scenarioStart = trades.indexOf('function PositionProfitScenarioSheet');
  const scenarioEnd = trades.indexOf('export default function TradesTab', scenarioStart);
  assert.ok(scenarioStart >= 0 && scenarioEnd > scenarioStart, 'scenario palette assertions must stay within the actual simulator');
  const scenarioSheet = trades.slice(scenarioStart, scenarioEnd);
  assert.match(positionProfitScenarioCss, /\.pps-panel\s*\{[^}]*background:\s*#101112;/, 'the scenario panel should use the current neutral-black report surface');
  assert.match(positionProfitScenarioCss, /\.pps-input-shell\s*\{[^}]*background:\s*#1a1b1d;/, 'the scenario input should use the report raised black surface');
  assert.match(positionProfitScenarioCss, /\.pps-shortcut\[aria-pressed="true"\]\s*\{[^}]*background:\s*#292a2c;[^}]*color:\s*#ededf0;/, 'selected price shortcuts should use a neutral selected state');
  assert.match(positionProfitScenarioCss, /\.pps-flat\s*\{[^}]*color:\s*#d4d4dc;/, 'zero profit should remain neutral rather than suggest a gain or loss');
  assert.match(positionProfitScenarioCss, /\.pps-position-marker\s*\{[^}]*border:\s*2px solid #aaaab2;[^}]*background:\s*#101112;/, 'static price markers should retain neutral gray outlines on black');
  assert.match(positionProfitScenarioCss, /\.pps-current-marker\s*\{[^}]*background:\s*#d2d4d7;/, 'the current-price marker should use the same neutral color as its breathing glow');
  assert.doesNotMatch(scenarioSheet + positionProfitScenarioCss, /#0b0f14|#f6b54b|#ffd166|#ffd18a|bg-gradient|linear-gradient|radial-gradient/, 'the isolated simulator should not retain its old navy, gold, or market-colored decorative gradient');
  assert.ok(scenarioSheet.includes("resultTone === 'flat' ? 'pps-flat'") && scenarioSheet.includes("markerGlowRgb = '210 212 215'"), 'flat outcomes and the current marker should stay neutral');
  assert.ok(scenarioSheet.includes('strongPnlClass(profit, marketColorMode)') && scenarioSheet.includes('pnlClass(deltaFromCurrent, marketColorMode)'), 'profit and change values must still respect the selected market color mode');
  assert.ok(trades.includes("isGenericLedgerTradeEntry ? 'stock-report-modal formal-trade-dialog'"), 'formal trades opt into the shared neutral-black report surface without changing TQQQ or wave shells');
  assert.ok(trades.includes('panelClassName="trade-order-dialog"'), 'order actions also opt into the report-modal surface');
  assert.equal(count(trades, /bg-\[#080808\]/g), 0, 'formal trades must not restore the superseded independent black panel');
  assert.equal(count(pnlReport, /bg-\[#0b0f14\]/g), 2, 'PnL bottom sheets should keep their existing depth colors');
  assert.equal(count(earningsCalendar, /bg-\[#0b0f14\]/g), 1, 'earnings modal should keep its existing depth color');
  assert.match(reviewGoalModalCss, /\.review-goal-modal\s*\{[^}]*background:\s*#101112;/, 'approved review dialogs should share the scoped neutral-black goal surface');
  assert.equal(count(reviewReadingDetails, /<ReviewGoalModal/g), 2, 'both reading details should use the goal-dialog palette');
  assert.doesNotMatch(reviewReadingDetails + reviewReadingDetailsCss, /UsFlagBackground|linear-gradient|radial-gradient|#f6b54b/, 'reading details should not add independent flag, gradient, or gold decorations');
  assert.ok(stockComparison.includes("import StockReportModal from './StockReportModal.jsx'"));
  assert.equal(count(stockComparison, /panelClassName="stock-comparison-dialog"/g), 2, 'method and share overlays must both opt into the same neutral report-dialog surface');
  assert.match(stockComparisonCss, /\.stock-comparison-tooltip\s*\{[^}]*background:\s*rgb\(24 25 27 \/ \.97\);/, 'comparison tooltip retains a raised neutral depth without restoring blue');
  assert.ok(valuation.includes('fill="#0b0f14" stroke="#ffd18a"'));
  assert.ok(ma200History.includes('stroke="#0b0f14"'));
  assert.ok(monthlyAssetTrendChart.includes('fill="#101318" stroke={CHART_COLOR}'));
  assert.ok(monthlyAssetTrendChart.includes('fill="#f5f7fb" stroke={CHART_LATEST_COLOR}'));
});
