// Instrument metadata only. No sample readings, scores or provider credentials.
export const MACRO_GROUPS = {
  rates: ['us2y', 'us5y', 'us10y', 'us30y', 'spread10y2y', 'real10y'],
  energy: ['wti', 'brent', 'naturalGas'],
  expectations: ['be5y', 'be10y'],
  dollarGold: ['dxy', 'gold'],
  stress: ['vix', 'vvix', 'move', 'hyOas', 'igOas'],
  liquidity: ['fedBalance', 'tga', 'rrp', 'sofr', 'effr', 'netLiquidity'],
};
export const MACRO_METRICS = Object.fromEntries([
  ['us2y', '美国2年期国债收益率', 'percent', 'bp'],
  ['us5y', '美国5年期国债收益率', 'percent', 'bp'],
  ['us10y', '美国10年期国债收益率', 'percent', 'bp'],
  ['us30y', '美国30年期国债收益率', 'percent', 'bp'],
  ['spread10y2y', '10年－2年国债收益率差', 'bp', 'bp'],
  ['real10y', '美国10年期国债实际收益率', 'percent', 'bp'],
  ['wti', '美国原油（WTI）', 'usd', 'percent'],
  ['brent', '布伦特原油（Brent）', 'usd', 'percent'],
  ['naturalGas', '天然气', 'usd', 'percent'],
  ['be5y', '5年期盈亏平衡通胀率', 'percent', 'bp'],
  ['be10y', '10年期盈亏平衡通胀率', 'percent', 'bp'],
  ['dxy', '美元指数（DXY）', 'index', 'percent'],
  ['gold', '黄金', 'usd', 'percent'],
  ['vix', '美股波动率指数（VIX）', 'index', 'percent'],
  ['vvix', '波动率波动指数（VVIX）', 'index', 'percent'],
  ['move', '美债波动率指数（MOVE）', 'index', 'percent'],
  ['hyOas', '高收益债信用利差（HY）', 'bp', 'bp'],
  ['igOas', '投资级债信用利差（IG）', 'bp', 'bp'],
  ['fedBalance', '美联储资产负债表', 'usdBn', 'usdBn', '周度'],
  ['tga', '美国财政部一般账户余额（TGA）', 'usdBn', 'usdBn', '周度'],
  ['rrp', '隔夜逆回购余额（RRP）', 'usdBn', 'usdBn'],
  ['sofr', '担保隔夜融资利率（SOFR）', 'percent', 'bp'],
  ['effr', '有效联邦基金利率（EFFR）', 'percent', 'bp'],
  ['netLiquidity', '净流动性', 'usdBn', 'usdBn', '周度'],
].map(([id, name, unit, changeUnit, frequency = '日度']) => [id, { id, name, unit, changeUnit, frequency }]));
